packages:
  - apps/*
  - packages/*
catalogs:
  web:
    vue: 3.5.24
    vite: 5.4.21
    vitepress: 1.6.4
    '@vue/server-renderer': 3.5.24
    '@slidev/cli': 52.8.0
    '@slidev/theme-default': 0.25.0
