import type { BaseInfoState, CustomIndexDetail } from './types'

export const mockCustomIndexDetail: CustomIndexDetail = {
  total: 77.52,
  max: 100.0,
  lastUpdated: '2025-06-16',
  frequencyNote: '每月 1 号和 16 号更新',
  dimensions: [
    {
      id: 'product',
      label: '产品竞争力',
      weight: 35,
      score: 85.25,
      trend: 'up',
      suggestionCount: 2,
      badge: 'good',
      action: 'suggestion',
    },
    {
      id: 'fulfillment',
      label: '店铺维护',
      weight: 5,
      score: 71.5,
      trend: 'flat',
      suggestionCount: 0,
      badge: 'good',
      action: 'detail',
    },
    {
      id: 'pricing',
      label: '交易经验',
      weight: 30,
      score: 68.35,
      trend: 'down',
      suggestionCount: 3,
      badge: 'warning',
      action: 'suggestion',
    },
    {
      id: 'promotion',
      label: '服务质量',
      weight: 15,
      score: 70.5,
      trend: 'flat',
      suggestionCount: 1,
      badge: 'warning',
      action: 'suggestion',
    },
    {
      id: 'service',
      label: '商家信誉',
      weight: 15,
      score: 79.4,
      trend: 'up',
      suggestionCount: 0,
      badge: 'good',
      action: 'detail',
    },
  ],
  penalties: [
    {
      id: 'platform',
      label: '平台扣分',
      value: -4.0,
      actionLabel: '查看方案',
      linkUrl: 'https://doc.weixin.qq.com/',
    },
  ],
  suggestions: [
    {
      id: 's1',
      title: '优化物流时效',
      description: '提升主流线路的签收准时率，减少超时订单。',
      tips: '优化后的项目可关注下次 Custom Index 分数更新。',
      linkText: '查看操作指引',
      linkUrl: 'https://doc.weixin.qq.com/',
    },
    {
      id: 's2',
      title: '补充商品评价',
      description: '鼓励买家填写真实评价，提升商家信誉分。',
      tips: '优化后的项目可关注下次 Custom Index 分数更新。',
      linkText: '查看操作指引',
      linkUrl: 'https://doc.weixin.qq.com/',
    },
  ],
}

export const mockBaseInfoState: BaseInfoState = {
  user: {
    name: 'Alice Zhang',
    greeting: 'Hi, Alice Zhang',
    id: 'ID:345879-0209',
    level: 'Lv.5 Custom Pro',
  },
  customIndex: {
    id: 'custom-index',
    label: 'custom Index',
    value: '95.6',
    secondary: 'PR: 90',
    description: '近 30 天成交额 +12%，位于品类 Top 3%',
  },
  beans: {
    id: 'beans',
    label: 'Beans',
    value: '1550',
    unit: '个',
    description: '每成交 100 USD 获得 2 Beans，可抵扣下次订单',
  },
  manager: {
    name: '刘婷',
    title: '招商经理 · 华东区域',
    avatar: 'https://placehold.co/96x96/png',
    qr: 'https://placehold.co/120x120/png',
    phone: '180-4567-8910',
    email: 'liuting@jousing.com',
  },
  customIndexDetail: mockCustomIndexDetail,
}
